spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/aims
    username: user
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false